// Database types matching schema.sql

export interface User {
  id: string;
  email: string;
  google_id: string;
  display_name?: string;
  profile_picture?: string;
  created_at: Date;
  updated_at: Date;
}

export interface PersonalityProfile {
  id: string;
  user_id: string;
  version: number;
  created_at: Date;
  updated_at: Date;
}

export type MBTIType =
  | 'INTJ' | 'INTP' | 'ENTJ' | 'ENTP'
  | 'INFJ' | 'INFP' | 'ENFJ' | 'ENFP'
  | 'ISTJ' | 'ISFJ' | 'ESTJ' | 'ESFJ'
  | 'ISTP' | 'ISFP' | 'ESTP' | 'ESFP';

export interface MBTIDistribution {
  profile_id: string;
  type: MBTIType;
  probability: number;  // 0.0 to 1.0
}

export type EnneagramType = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
  | '1w2' | '1w9' | '2w1' | '2w3' | '3w2' | '3w4' | '4w3' | '4w5'
  | '5w4' | '5w6' | '6w5' | '6w7' | '7w6' | '7w8' | '8w7' | '8w9' | '9w8' | '9w1';

export interface EnneagramDistribution {
  profile_id: string;
  type: EnneagramType;
  probability: number;  // 0.0 to 1.0
}

export type StatementCategory =
  | 'work_style'
  | 'communication'
  | 'decision_making'
  | 'social'
  | 'stress_response'
  | 'values'
  | 'habits'
  | 'other';

export type StatementSource =
  | 'llm_inferred'      // Generated by LLM from personality types
  | 'user_provided'     // User wrote this themselves
  | 'questionnaire'     // From initial assessment
  | 'chatgpt_import';   // From ChatGPT prompt analysis

export interface PersonalityStatement {
  id: string;
  user_id: string;
  statement: string;          // Max 500 chars
  credence: -1 | 0 | 1;       // V1: Binary only (-1=disagree, 0=not validated, 1=agree)
  category?: StatementCategory;
  source: StatementSource;
  user_validated: boolean;
  created_at: Date;
  updated_at: Date;
}

export type ArtifactType =
  | 'workday_guide'
  | 'dating_profile'
  | 'conflict_style'
  | 'communication_guide'
  | 'decision_framework';

export interface Artifact {
  id: string;
  user_id: string;
  type: ArtifactType;
  title: string;
  content: string;              // Markdown
  prompt: string;               // The template used (predefined only for V1)
  generated_by: 'claude-sonnet-4.5' | 'gpt-4o';
  created_at: Date;
  updated_at: Date;
}

export interface RefreshToken {
  id: string;
  user_id: string;
  token: string;
  expires_at: Date;
  created_at: Date;
}

export interface LLMUsage {
  id: string;
  user_id: string;
  operation: string;
  model: string;
  tokens_input: number;
  tokens_output: number;
  cost_usd: number;
  created_at: Date;
}

// API Request/Response types

export interface SuccessResponse<T> {
  data: T;
}

export interface ErrorResponse {
  error: {
    code: string;
    message: string;
    details?: any;
    retryAfter?: number;
  };
}

export interface GenerateArtifactRequest {
  type: ArtifactType;
}

export interface GenerateArtifactResponse {
  id: string;
  type: string;
  title: string;
  content: string;
  generatedBy: string;
  createdAt: string;
}

export interface UpdateStatementRequest {
  credence: -1 | 0 | 1;
}

export interface StatementResponse {
  id: string;
  statement: string;
  credence: number;
  userValidated: boolean;
  source: string;
  category?: string;
  createdAt: string;
}

export interface UpdateMBTIRequest {
  distribution: Array<{
    type: MBTIType;
    probability: number;
  }>;
  expectedVersion: number;
}

export interface UpdateMBTIResponse {
  version: number;
  distribution: Array<{
    type: MBTIType;
    probability: number;
  }>;
}

export interface UpdateEnneagramRequest {
  distribution: Array<{
    type: EnneagramType;
    probability: number;
  }>;
  expectedVersion: number;
}

export interface UpdateEnneagramResponse {
  version: number;
  distribution: Array<{
    type: EnneagramType;
    probability: number;
  }>;
}

// JWT token payload
export interface JWTPayload {
  userId: string;
  email: string;
}
